### ISSUE TITLE
Going to an incorrect url in docs should show an error page

### ISSUE THREAD

**Issue by azeey** [gazebo-web/gazebosim-web-frontend#16]
Going to an incorrect url, eg. https://gazebosim.org/docs/bad_url, currently goes to the default page (https://gazebosim.org/docs) instead of showing an error page. This can lead to confusion when links with typos are followed and land on something unrelated to the original link. It would be better to show an error page so that the user knows to check for typos or make an effort to find the intended page themselves.

Urls that contain the version name have a different behavior. For example, https://gazebosim.org/docs/harmonic/bad_url goes to https://gazebosim.org/not-found which actually just loads https://gazebosim.org/. Here, https://gazebosim.org/not-found should be a 404 page.

**Comment by mabelzhang** [comment]
~~Implementation hint:~~

~~For the non-versioned URL (first part of this ticket), I THINK it might be happening in this else-clause:~~

https://github.com/gazebo-web/gazebosim-web-frontend/blob/4da2478c9ed82db0ae0c3f21bb70627d6a7a91ea/src/app/doc/doc.component.ts#L103-L106

~~`href` probably contains the subpage name.~~
~~Instead of just returning `docs/version/subPage`, it should check if the subpage exists first, i.e. in `this.pages[i].name`. If not, then it should return `not-found`.~~

~~I broke my local preview again (it seems flaky for me, I don't know why, sometimes my docs page is just blank), so I couldn't test my implementation.~~

**Comment by mabelzhang** [comment]
Well, if I read what I said above, there's an obvious contradiction, duh, you don't fix the non-versioned URL in a block that has the word `version` in it @_@
But I did find the fix for real now, in PR #27 :)
